CELL = 16
LEVEL_WIDTH = 15
LEVEL_HEIGHT = 10

BOARD_OFFSET_X = 9.5
BOARD_OFFSET_Y = 4.5

MODE_PLAY = 1
MODE_CREATE = 2

AVATAR_ID_SNAIL = 1
AVATAR_ID_CAT = 2
AVATAR_ID_MOUSE = 3
AVATAR_ID_RACCOON = 4
AVATAR_ID_NIL = 5
AVATAR_ID_RDK = 6
NUM_AVATARS = 4
AVATAR_NAMES = {
	"Suave Snail",
	"Charming Cat",
	"Mindful Mouse",
	"Reliable Raccoon"
}

MAX_LEVEL_NAME_SIZE = 161
SIDEBAR_WIDTH = 221
SEPARATOR_WIDTH = 24

GAME_NAME = "Sketch, Share, Solve"
