CELL = 16

BOARD_OFFSET_X = 152
BOARD_OFFSET_Y = 72

MODE_PLAY = 1
MODE_CREATE = 2

Z_INDEX_BOARD = 5
Z_INDEX_TITLE = 5

Z_INDEX_BOARD_NUMBERS = 10

Z_INDEX_DIALOG = 20
Z_INDEX_CURSOR = 20

Z_INDEX_SIDEBAR = 50

Z_INDEX_AVATAR = 60

AVATAR_ID_SNAIL = 1
AVATAR_ID_CAT = 2
AVATAR_ID_MOUSE = 3
AVATAR_ID_RACCOON = 4
AVATAR_ID_NIL = 5
AVATAR_ID_RDK = 6
NUM_AVATARS = 4
AVATAR_NAMES = {
	"Suave Snail",
	"Charming Cat",
	"Mindful Mouse",
	"Reliable Raccoon"
}
AVATAR_FOLDER_NAME = "avatars/"

MAX_LEVEL_NAME_SIZE = 161
SIDEBAR_WIDTH = 221
SEPARATOR_WIDTH = 24
AVATAR_OFFSET = SIDEBAR_WIDTH - SEPARATOR_WIDTH - 1

PLAYER_ID_SHOW_NAME = "NAME"

GAME_NAME = "Sketch, Share, Solve"
